#!/bin/bash 

# Write in memory
LIB="/Library/CodeLoader"
CONF="$LIB/conf"
BUNDLES="$LIB/bundles"
CACHED="$LIB/cache"
CACHEF="$CACHED/bg.codeloaderbundlelist"
SIGNED_ONLY="false"
EXTENSION="bg.loaderb"
LOADED_REPORT="/tmp/CodeLoader.Background.LoadedBundles"
NOT_LOADED_REPORT="/tmp/CodeLoader.Background.ErrorBundle"

if [[ ! -f "/tmp/CodeLoader.Background.operationDone" ]]; then
	echo "Operation not done yet."
	exit 0
fi

if [[ ! -f "$CACHED/bg.runpass" ]]; then
	echo "Run pass failed. Safe mode triggered."
	sudo touch "$CONF/bg/safeboot_boot"
	sudo rm -f "$CACHED/bg.runpass"
	exit 3
fi
sudo rm -f "$CACHED/bg.runpass"

echo "[$(date)] Entry Start" >> "$LOADED_REPORT"
echo "[$(date)] Entry Start" >> "$NOT_LOADED_REPORT"

# Run loop
cd "$BUNDLES"
if [[ -z "$(ls $BUNDLES/*.$EXTENSION)" ]]; then
	echo "[$(date)] Entry End" >> "$LOADED_REPORT"
	echo "[$(date)] Entry End" >> "$NOT_LOADED_REPORT"
	sudo touch "/tmp/CodeLoader.Background.operationComplete"
	sudo touch "$CACHED/bg.runpass"
	echo "No bundles loaded. Terminating..."
	exit 0
fi
for f in *.$EXTENSION; do
	echo "Loading $f..."
	sudo "$f"/exec "$BUNDLES/$f" &
	EXITCODE=$?
	if [[ $EXITCODE -ne 0 ]]; then
		echo "ERROR: An error occured while loading $ID."
		echo "$f" >> "$NOT_LOADED_REPORT"
		exit -1
	else
		echo "$f" >> "$LOADED_REPORT"
	fi
done
echo "[$(date)] Entry End" >> "$LOADED_REPORT"
echo "[$(date)] Entry End" >> "$NOT_LOADED_REPORT"

# Write flag
sudo touch "/tmp/CodeLoader.Background.operationComplete"
sudo touch "/tmp/CodeLoader.Background.operationDone"
sudo touch "$CACHED/bg.runpass"
exit 0